import { Injectable, OnApplicationBootstrap, OnModuleDestroy, Logger } from '@nestjs/common';
import { execFile } from 'child_process';
import { promisify } from 'util';
import * as path from 'path';
import * as fs from 'fs';
import { PrismaService } from '../../prisma/prisma.service';

const execFileAsync = promisify(execFile);
const DATA_DIR = process.env.KRYPTALIS_DATA_DIR || path.join(process.cwd(), '.kryptalis');
const PROXY_DIR = path.join(DATA_DIR, 'reverse-proxy');
const CONTAINER_NAME = 'kryptalis-caddy';

/**
 * Generates a Caddyfile from the current domains↔applications mapping,
 * runs Caddy in a docker container on host ports 80/443, and reloads on changes.
 *
 * For *.local domains we generate a plain HTTP block (no Let's Encrypt).
 * For real domains we let Caddy auto-issue Let's Encrypt certificates.
 *
 * Strategy: Caddy reverse_proxy to host.docker.internal:<port>
 * (works on Docker Desktop Windows/Mac; on Linux production we'd add the
 * `extra_hosts: host-gateway` mapping at compose level).
 */
@Injectable()
export class ReverseProxyService implements OnApplicationBootstrap, OnModuleDestroy {
  private readonly logger = new Logger(ReverseProxyService.name);
  private sslSyncInterval: ReturnType<typeof setInterval> | null = null;

  constructor(private prisma: PrismaService) {
    if (!fs.existsSync(PROXY_DIR)) fs.mkdirSync(PROXY_DIR, { recursive: true });
  }

  async onApplicationBootstrap() {
    try {
      // Ensure the Caddyfile exists so the container (managed by the root
      // docker-compose) can mount it successfully. If the file is empty/missing,
      // we seed a placeholder, then regenerate from the live DB state.
      this.ensureCaddyfile();
      await this.regenerate();
    } catch (e: any) {
      this.logger.warn(`Caddy bootstrap deferred: ${e?.message || e}`);
    }
    // Background SSL status reconciliation — catches certs issued asynchronously
    // by Caddy after a regenerate() call OR after manual changes.
    this.sslSyncInterval = setInterval(() => {
      this.syncSslStatuses().catch(() => {});
    }, 60_000);
  }

  onModuleDestroy() {
    if (this.sslSyncInterval) {
      clearInterval(this.sslSyncInterval);
      this.sslSyncInterval = null;
    }
  }

  private ensureCaddyfile() {
    const caddyfile = path.join(PROXY_DIR, 'Caddyfile');
    if (fs.existsSync(caddyfile)) return;
    const email = this.resolveAcmeEmail();
    const seed = `# Auto-generated by Kryptalis — do not edit manually.
{
  admin :2019
${email ? `  email ${email}\n` : ''}}
:80 {
  respond "Kryptalis: no domain configured yet." 404
}
`;
    fs.writeFileSync(caddyfile, seed);
  }

  /**
   * Caddy now lives in the root docker-compose. These methods proxy to that
   * container. start/stop become docker-compose calls at repo root.
   */
  async ensureRunning() {
    const current = await this.status();
    if (current.running) {
      return { ok: true, running: true, status: current.status, message: 'Caddy is already running' };
    }
    // Caddy is managed by the root compose. From inside the API container we
    // can't reach the host's compose file, but we CAN start the container by
    // name via the mounted docker socket. (Compose just labels the containers;
    // `docker start` works the same.)
    try {
      await execFileAsync('docker', ['start', CONTAINER_NAME], { timeout: 30_000 });
    } catch (e: any) {
      this.logger.warn(`Could not start caddy: ${e?.message}`);
      return { ok: false, running: false, status: 'error', message: e?.message || 'Failed to start Caddy' };
    }
    const after = await this.status();
    return { ok: after.running, running: after.running, status: after.status, message: after.running ? 'Caddy started' : 'Caddy did not come up' };
  }

  async stop() {
    try {
      await execFileAsync('docker', ['stop', CONTAINER_NAME], { timeout: 30_000 });
      return { ok: true, running: false, status: 'stopped', message: 'Caddy stopped' };
    } catch (e: any) {
      return { ok: false, running: false, status: 'error', message: e?.message || 'Failed to stop Caddy' };
    }
  }

  // ── status ────────────────────────────────────────────────────────
  //
  // We use `docker ps --filter` rather than `docker inspect <name>` because:
  //   1. ps succeeds even when the container doesn't exist (empty output)
  //   2. inspect needs the EXACT name; compose may prefix it depending on version
  //
  // We also fall back to looking up by image so a Caddy container started with
  // a different name (legacy installs) is still detected.
  async status() {
    try {
      const { stdout } = await execFileAsync(
        'docker',
        ['ps', '-a', '--filter', `name=${CONTAINER_NAME}`, '--format', '{{.State}}|{{.Status}}|{{.Names}}'],
        { timeout: 5000 },
      );
      const line = stdout.trim().split('\n').find(Boolean);
      if (!line) return { running: false, status: 'not-found' };
      const [state, statusLine, name] = line.split('|');
      const running = state === 'running';
      return { running, status: state || 'unknown', detail: statusLine, name };
    } catch (e: any) {
      this.logger.warn(`status check failed: ${e?.message}`);
      return { running: false, status: 'error', message: e?.message };
    }
  }

  // ── regenerate + reload ───────────────────────────────────────────

  async regenerate() {
    // EVERY domain owned by a project — even those not yet linked to an app.
    // Reserved domains still get a Caddy block so Let's Encrypt provisions the cert
    // in advance (the user gets a green padlock the moment they wire it to an app).
    const allDomains = await this.prisma.domain.findMany({
      include: { application: { select: { id: true, name: true, port: true } } },
    });

    // Some marketplace apps listen on HTTPS by default with a self-signed
    // cert (Portainer on 9443 is the canonical case). When we reverse_proxy
    // to them in plain HTTP, Caddy gets a TLS alert and returns 502. Switch
    // the upstream to https:// with `tls_insecure_skip_verify` so it works.
    const HTTPS_UPSTREAM_PORTS = new Set([443, 8443, 9443]);
    // mail server domains — we provision a Let's Encrypt cert for mail.<apex>
    // so the mail server container can re-use it.
    const mailServers = await this.prisma.mailServer.findMany({
      include: { domain: { select: { domain: true } } },
    });

    // ACME contact email — Let's Encrypt refuses bogus addresses ("localhost",
    // empty, etc.) so we derive a sensible default from PUBLIC_API_URL when the
    // operator hasn't set ACME_EMAIL explicitly.
    const acmeEmail = this.resolveAcmeEmail();

    const blocks: string[] = [
      '# Auto-generated by Kryptalis — do not edit manually.',
      '{',
      '  admin :2019',
    ];
    // Only emit `email` when we have something Let's Encrypt accepts.
    // Without it, Caddy still gets a cert (just no expiry notices).
    if (acmeEmail) blocks.push(`  email ${acmeEmail}`);
    blocks.push('}');
    blocks.push('');

    let activeCount = 0;
    let reservedCount = 0;
    const newStatusByDomainId: Record<string, 'ACTIVE' | 'PENDING'> = {};

    for (const d of allDomains) {
      const host = d.domain;
      const isLocal = this.isLocalHostname(host);
      const port = d.application?.port ?? null;
      const linked = !!d.applicationId && !!port;

      blocks.push(linked
        ? `# ${host} → app ${d.application?.name} (host port ${port})`
        : `# ${host} → reserved (no app linked yet)`);

      const upstreamHttps = linked && port !== null && HTTPS_UPSTREAM_PORTS.has(port);
      const proxyDirective = upstreamHttps
        ? `  reverse_proxy https://host.docker.internal:${port} {\n    transport http {\n      tls\n      tls_insecure_skip_verify\n    }\n  }`
        : `  reverse_proxy host.docker.internal:${port}`;

      if (isLocal) {
        blocks.push(`http://${host} {`);
        if (linked) {
          blocks.push(proxyDirective);
        } else {
          blocks.push(`  respond "Domain reserved in Kryptalis — link it to an app to serve traffic." 503`);
        }
        blocks.push(`}`);
      } else {
        // real domain: Caddy auto-provisions Let's Encrypt over :80/:443
        // even when no app is linked yet — so the cert is ready when the user
        // wires the app in.
        blocks.push(`${host} {`);
        if (linked) {
          blocks.push(proxyDirective);
        } else {
          blocks.push(`  respond "Domain reserved in Kryptalis — link it to an app to serve traffic." 503`);
        }
        blocks.push(`}`);
      }
      blocks.push('');

      if (linked) {
        newStatusByDomainId[d.id] = 'ACTIVE';
        activeCount++;
      } else {
        // The cert is being provisioned but no app routes traffic — call this
        // PENDING in the DB so the UI shows "waiting on app link".
        newStatusByDomainId[d.id] = 'PENDING';
        reservedCount++;
      }
    }

    // mail.<apex> routes — only purpose is to obtain Let's Encrypt certs for the mail server.
    // The mail server itself reads the cert files from the shared Caddy volume.
    for (const ms of mailServers) {
      const apex = ms.domain.domain;
      if (this.isLocalHostname(apex)) continue;
      const mailHost = `mail.${apex}`;
      blocks.push(`# ${mailHost} → cert provisioning for mail server`);
      blocks.push(`${mailHost} {`);
      blocks.push(`  respond "Kryptalis mail server. Use IMAP/SMTP clients, not HTTP." 200`);
      blocks.push(`}`);
      blocks.push('');
    }

    // catch-all fallback so connections to any unconfigured Host:port 80 don't 502
    blocks.push(':80 {');
    blocks.push('  respond "Domain not configured in Kryptalis." 404');
    blocks.push('}');

    const caddyfile = blocks.join('\n');
    fs.writeFileSync(path.join(PROXY_DIR, 'Caddyfile'), caddyfile);

    // try graceful reload via Caddy admin API inside the container
    try {
      await execFileAsync(
        'docker',
        ['exec', CONTAINER_NAME, 'caddy', 'reload', '--config', '/etc/caddy/Caddyfile'],
        { timeout: 15_000 },
      );
      this.logger.log(`Caddy reloaded — ${activeCount} active, ${reservedCount} reserved`);
    } catch (e: any) {
      // fallback: restart container if reload failed
      this.logger.warn(`reload failed (${e?.message}); restarting container`);
      try {
        await execFileAsync('docker', ['restart', CONTAINER_NAME], { timeout: 30_000 });
      } catch {}
    }

    // sync DB statuses + persist for visibility
    await Promise.all(
      Object.entries(newStatusByDomainId).map(([id, status]) =>
        this.prisma.domain.update({ where: { id }, data: { status } }),
      ),
    );

    // Caddy emits ACME challenges async — schedule a few SSL status syncs after
    // the reload so the dashboard sees the green padlock without manual resync.
    [10_000, 30_000, 60_000, 120_000].forEach((ms) => {
      setTimeout(() => this.syncSslStatuses().catch(() => {}), ms);
    });

    return { domains: activeCount, caddyfile };
  }

  /**
   * Ask Caddy which domains have a valid cert and update Domain.sslStatus in DB.
   * Caddy stores certs under /data/caddy/certificates/<issuer>/<domain>/. The
   * mere presence of <domain>.crt means the cert is issued.
   */
  async syncSslStatuses() {
    const domains = await this.prisma.domain.findMany({
      select: { id: true, domain: true, sslStatus: true },
    });
    if (!domains.length) return { updated: 0 };

    let updated = 0;
    let checked = 0;
    for (const d of domains) {
      // skip local hostnames — Caddy uses its internal CA, not Let's Encrypt
      if (this.isLocalHostname(d.domain)) continue;
      checked++;
      const hasCert = await this.hasIssuedCert(d.domain);
      const newStatus = hasCert ? 'ACTIVE' : 'PENDING';
      if (d.sslStatus !== newStatus) {
        await this.prisma.domain.update({
          where: { id: d.id },
          data: {
            sslStatus: newStatus as any,
            sslExpiresAt: hasCert ? new Date(Date.now() + 90 * 24 * 3600 * 1000) : null,
          },
        });
        updated++;
        this.logger.log(`SSL: ${d.domain} → ${newStatus}`);
      }
    }
    this.logger.debug(`SSL sync: ${checked} checked, ${updated} updated`);
    return { updated, checked };
  }

  private async hasIssuedCert(host: string): Promise<boolean> {
    try {
      // Look for the cert file inside the Caddy container. The exact subdir
      // varies by CA (acme-v02.api.letsencrypt.org-directory for LE prod,
      // acme-staging-v02… for staging) so we glob.
      const { stdout } = await execFileAsync(
        'docker',
        ['exec', CONTAINER_NAME, 'sh', '-c',
          `ls /data/caddy/certificates/*/${host}/${host}.crt 2>/dev/null | head -1`],
        { timeout: 5000 },
      );
      return stdout.trim().length > 0;
    } catch {
      return false;
    }
  }

  // ── helpers ───────────────────────────────────────────────────────

  /**
   * Pick the email Caddy registers with Let's Encrypt.
   *
   * Resolution order:
   *   1. ACME_EMAIL env var (operator override)
   *   2. admin@<apex of PUBLIC_API_URL> if it's a real domain
   *   3. admin@<first registered domain in DB>
   *   4. last resort: do not emit an `email` line (Caddy then prompts for one
   *      via internal CA fallback — better than feeding LE garbage and getting
   *      rate-limited).
   *
   * NEVER returns "localhost" — LE rejects it.
   */
  private resolveAcmeEmail(): string | null {
    if (process.env.ACME_EMAIL) return process.env.ACME_EMAIL;
    try {
      if (process.env.PUBLIC_API_URL) {
        const host = new URL(process.env.PUBLIC_API_URL).hostname;
        if (host && !/^\d+\.\d+\.\d+\.\d+$/.test(host) && host !== 'localhost') {
          return `admin@${host}`;
        }
      }
    } catch {}
    return null;
  }

  private isLocalHostname(host: string): boolean {
    return (
      host.endsWith('.local') ||
      host.endsWith('.localhost') ||
      host === 'localhost' ||
      host.endsWith('.test') ||
      host.endsWith('.invalid') ||
      /^\d+\.\d+\.\d+\.\d+$/.test(host)
    );
  }
}
