/**
 * Supported PHP runtime versions for the PHP_SITE hosting type. Each maps to an
 * official `php:<version>-apache` Docker image tag (Debian-based, mod_php).
 *
 * Ordered newest-first so the UI dropdown defaults to the most current release.
 * Keep this list in sync with the tags Docker Hub still publishes — dropping an
 * EOL tag here stops new sites using it without touching existing deploys.
 */
export const SUPPORTED_PHP_VERSIONS = ['8.3', '8.2', '8.1', '8.0', '7.4'] as const;

export type PhpVersion = (typeof SUPPORTED_PHP_VERSIONS)[number];

/** Default chosen when the user doesn't pick one (latest stable). */
export const DEFAULT_PHP_VERSION: PhpVersion = '8.3';

/** Internal port the php:*-apache image listens on (mod_php under Apache). */
export const PHP_SITE_CONTAINER_PORT = 80;

export function isSupportedPhpVersion(v: string | null | undefined): v is PhpVersion {
  return !!v && (SUPPORTED_PHP_VERSIONS as readonly string[]).includes(v);
}

/**
 * Generated Dockerfile for a PHP_SITE app. One template; the PHP version is a
 * build ARG so 7.4–8.3 share it. PHP_VERSION is NOT secret, so it's set in
 * build.args by the deploy method (never via injectComposeEnv).
 *
 * The stock `php:<ver>-apache` image ships with NO database drivers and almost
 * none of the extensions real apps need — `new PDO('mysql:...')` fails with
 * "could not find driver". So we bundle:
 *   - DB drivers: pdo_mysql + mysqli (MySQL & MariaDB), pdo_pgsql + pgsql (Postgres)
 *   - common web pack: gd (image processing), zip, intl, opcache, bcmath
 * These cover WordPress, Laravel, Symfony, PrestaShop, Drupal, etc.
 *
 * docker-php-ext-install compiles against system -dev libs, so we apt-get them
 * first (libpq for pgsql, libpng/libjpeg/libfreetype for gd, libzip for zip,
 * libicu for intl), configure gd with jpeg+freetype, then install — and clean
 * the apt lists in the same layer to keep the image lean. mod_rewrite is
 * enabled for .htaccess-style pretty URLs (WordPress permalinks, Laravel).
 *
 * The docroot is bind-mounted at runtime, so the image itself ships empty.
 */
export const PHP_SITE_DOCKERFILE = `# syntax=docker/dockerfile:1
# Generated by DockControl for a PHP_SITE app. Do not edit — regenerated on redeploy.
ARG PHP_VERSION=${DEFAULT_PHP_VERSION}
FROM php:\${PHP_VERSION}-apache

# System libraries the bundled PHP extensions compile against.
RUN apt-get update && apt-get install -y --no-install-recommends \\
      libpq-dev libpng-dev libjpeg-dev libfreetype6-dev libzip-dev libicu-dev \\
 && docker-php-ext-configure gd --with-jpeg --with-freetype \\
 && docker-php-ext-install -j"\$(nproc)" \\
      pdo_mysql mysqli pdo_pgsql pgsql gd zip intl opcache bcmath \\
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Pretty URLs (.htaccess rewrites — WordPress permalinks, Laravel, etc.).
RUN a2enmod rewrite

EXPOSE 80
`;
