import { describe, it, expect } from 'vitest';
import * as yaml from 'js-yaml';
import {
  isPhpMarketplace,
  isPhpMarketplaceSlug,
  isPhpConfigurable,
  marketplaceSlugOf,
  buildPhpIniSideFile,
  buildPhpIniSideFileForSlug,
  ensurePhpIniMount,
  PRESTASHOP_DEFAULT_INI,
} from './php-ini-marketplace';
import { PHP_INI_SIDEFILE, COMPOSE_TEMPLATES, PHP_MARKETPLACE_APPS } from '../marketplace/templates';

const presta = (over: any = {}) => ({
  id: 'abcdef012345xyz',
  containerName: 'dockcontrol-prestashop-abcdef012345',
  framework: 'DOCKER_COMPOSE',
  ...over,
});

describe('marketplaceSlugOf', () => {
  it('recovers the slug from the container name + id', () => {
    expect(marketplaceSlugOf(presta())).toBe('prestashop');
    expect(marketplaceSlugOf({ id: 'idididididid99', containerName: 'dockcontrol-wordpress-idididididid' }))
      .toBe('wordpress');
  });
  it('undoes the redis→redis-app special case', () => {
    expect(marketplaceSlugOf({ id: 'x'.repeat(20), containerName: 'dockcontrol-redis-app-' + 'x'.repeat(12) }))
      .toBe('redis');
  });
  it('returns null for non-dockcontrol container names', () => {
    expect(marketplaceSlugOf({ id: 'a', containerName: 'random-thing' })).toBeNull();
    expect(marketplaceSlugOf({})).toBeNull();
  });
  it('does NOT false-positive a classic app named "wordpress" (no -id12 suffix)', () => {
    // Classic git/Docker apps use containerName `dockcontrol-<slug>` with NO
    // per-instance suffix — must not be mistaken for a marketplace install.
    expect(marketplaceSlugOf({ id: 'someappid1234', containerName: 'dockcontrol-wordpress' })).toBeNull();
    expect(isPhpMarketplace({ id: 'someappid1234', containerName: 'dockcontrol-wordpress', framework: 'DOCKER' }))
      .toBe(false);
    expect(isPhpConfigurable({ id: 'someappid1234', containerName: 'dockcontrol-wordpress', framework: 'DOCKER' }))
      .toBe(false);
  });
});

describe('isPhpMarketplace / isPhpConfigurable', () => {
  it('true for the 4 PHP marketplace apps', () => {
    for (const slug of ['prestashop', 'wordpress', 'phpmyadmin', 'nextcloud']) {
      expect(isPhpMarketplaceSlug(slug)).toBe(true);
    }
  });
  it('false for non-PHP marketplace apps', () => {
    expect(isPhpMarketplaceSlug('redis')).toBe(false);
    expect(isPhpMarketplaceSlug('grafana')).toBe(false);
    expect(isPhpMarketplace({ id: 'a', containerName: 'dockcontrol-redis-app-aaaaaaaaaaaa' })).toBe(false);
  });
  it('isPhpConfigurable also true for native PHP_SITE apps', () => {
    expect(isPhpConfigurable({ framework: 'PHP_SITE' })).toBe(true);
    expect(isPhpConfigurable(presta())).toBe(true);
    expect(isPhpConfigurable({ framework: 'DOCKER', id: 'a', containerName: 'dockcontrol-grafana-aaaaaaaaaaaa' }))
      .toBe(false);
  });
});

describe('buildPhpIniSideFile', () => {
  it('always returns the .ini for a PHP marketplace app (empty config → header only)', () => {
    const sf = buildPhpIniSideFile(presta({ phpIni: null }));
    expect(Object.keys(sf)).toEqual([PHP_INI_SIDEFILE]);
    expect(sf[PHP_INI_SIDEFILE]).toMatch(/Generated by DockControl/);
  });
  it('renders the user directives', () => {
    const sf = buildPhpIniSideFile(presta({ phpIni: { memory_limit: '512M', short_open_tag: 'Off' } }));
    expect(sf[PHP_INI_SIDEFILE]).toContain('memory_limit = 512M');
    expect(sf[PHP_INI_SIDEFILE]).toContain('short_open_tag = Off');
  });
  it('returns {} for a non-PHP app', () => {
    expect(buildPhpIniSideFile({ id: 'a', containerName: 'dockcontrol-grafana-aaaaaaaaaaaa' })).toEqual({});
  });
  it('slug variant applies the PrestaShop default ini', () => {
    const sf = buildPhpIniSideFileForSlug('prestashop', PRESTASHOP_DEFAULT_INI);
    expect(sf[PHP_INI_SIDEFILE]).toContain('short_open_tag = Off');
  });
});

describe('ensurePhpIniMount', () => {
  const composeWithout = yaml.dump({
    services: {
      prestashop: {
        image: 'prestashop/prestashop:latest',
        volumes: ['prestashop_data:/var/www/html'],
      },
    },
  });

  const HOST = '/opt/dockcontrol/apps/prestashop-abcdef012345';

  it('injects the .ini mount with an ABSOLUTE bind source (no placeholder)', () => {
    const { compose, changed } = ensurePhpIniMount(presta(), composeWithout, HOST);
    expect(changed).toBe(true);
    const doc: any = yaml.load(compose);
    const vols: string[] = doc.services.prestashop.volumes;
    const mount = vols.find((v) => v.includes('/usr/local/etc/php/conf.d/' + PHP_INI_SIDEFILE));
    expect(mount).toBeTruthy();
    // The bind SOURCE must be the resolved absolute path — NOT __HOST_APP_DIR__
    // (which would make Docker create a junk dir relative to the compose).
    expect(mount).toBe(`${HOST}/${PHP_INI_SIDEFILE}:/usr/local/etc/php/conf.d/${PHP_INI_SIDEFILE}:ro`);
    expect(mount).not.toContain('__HOST_APP_DIR__');
    // existing volume preserved
    expect(vols).toContain('prestashop_data:/var/www/html');
  });

  it('is idempotent — already-mounted compose is untouched', () => {
    const once = ensurePhpIniMount(presta(), composeWithout, HOST).compose;
    const { changed } = ensurePhpIniMount(presta(), once, HOST);
    expect(changed).toBe(false);
  });

  it('treats an install-time host-path-rewritten mount as already present', () => {
    const rewritten = yaml.dump({
      services: {
        prestashop: {
          volumes: [
            'prestashop_data:/var/www/html',
            `${HOST}/${PHP_INI_SIDEFILE}:/usr/local/etc/php/conf.d/${PHP_INI_SIDEFILE}:ro`,
          ],
        },
      },
    });
    expect(ensurePhpIniMount(presta(), rewritten, HOST).changed).toBe(false);
  });

  it('leaves a non-PHP app compose untouched', () => {
    const { changed } = ensurePhpIniMount(
      { id: 'a', containerName: 'dockcontrol-grafana-aaaaaaaaaaaa' },
      composeWithout,
      HOST,
    );
    expect(changed).toBe(false);
  });

  it('does not crash on unparseable compose', () => {
    const bad = ':\n  - [unbalanced';
    const { compose, changed } = ensurePhpIniMount(presta(), bad, HOST);
    expect(changed).toBe(false);
    expect(compose).toBe(bad);
  });
});

// Round-trip against the REAL shipped templates: every PHP marketplace compose
// must (a) parse, (b) already carry the .ini mount on the right service, and
// (c) be idempotent under ensurePhpIniMount (no double-mount).
describe('shipped PHP marketplace templates carry the .ini mount', () => {
  for (const [slug, def] of Object.entries(PHP_MARKETPLACE_APPS)) {
    it(`${slug}: compose mounts ${PHP_INI_SIDEFILE} on service "${def.service}"`, () => {
      const raw = COMPOSE_TEMPLATES[slug]?.compose;
      expect(raw, `template ${slug} exists`).toBeTruthy();
      // Substitute the install-time placeholders so YAML is clean.
      const rendered = raw!
        .replace(/__INSTANCE_ID__/g, 'abcdef012345')
        .replace(/__HOST_PORT__/g, '8080')
        .replace(/__HOST_APP_DIR__/g, '/opt/dockcontrol/apps/' + slug + '-abcdef012345')
        .replace(/__RANDOM_PASSWORD(_\d)?__/g, 'pw');
      const doc: any = yaml.load(rendered);
      const vols: string[] = doc.services[def.service].volumes || [];
      const target = `${def.confDir}/${PHP_INI_SIDEFILE}`;
      expect(vols.some((v) => v.includes(target)), `${slug} has the mount`).toBe(true);
      // Idempotent: ensurePhpIniMount must NOT add a second one.
      const { changed } = ensurePhpIniMount(
        { id: 'abcdef012345xyz', containerName: `dockcontrol-${slug === 'redis' ? 'redis-app' : slug}-abcdef012345` },
        rendered,
        '/opt/dockcontrol/apps/' + slug + '-abcdef012345',
      );
      expect(changed, `${slug} mount is idempotent`).toBe(false);
    });
  }
});

// Full PrestaShop round-trip: render the .ini a user would get and assert the
// exact directives land — this is what unblocks the installer.
describe('PrestaShop php.ini round-trip', () => {
  it('default install renders short_open_tag = Off', () => {
    const sf = buildPhpIniSideFileForSlug('prestashop', PRESTASHOP_DEFAULT_INI);
    expect(sf[PHP_INI_SIDEFILE]).toContain('short_open_tag = Off');
  });
  it('user overrides render every directive of the full pack', () => {
    const sf = buildPhpIniSideFile(
      presta({
        phpIni: {
          memory_limit: '512M',
          upload_max_filesize: '128M',
          post_max_size: '128M',
          max_execution_time: '300',
          timezone: 'Europe/Paris',
          max_input_vars: '20000',
          short_open_tag: 'Off',
        },
      }),
    );
    const ini = sf[PHP_INI_SIDEFILE];
    expect(ini).toContain('memory_limit = 512M');
    expect(ini).toContain('upload_max_filesize = 128M');
    expect(ini).toContain('post_max_size = 128M');
    expect(ini).toContain('max_execution_time = 300');
    expect(ini).toContain('date.timezone = Europe/Paris');
    expect(ini).toContain('max_input_vars = 20000');
    expect(ini).toContain('short_open_tag = Off');
  });
});
