import { describe, it, expect } from 'vitest';
import {
  buildPhpDockerfile,
  buildPhpIni,
  buildNginxConf,
  sanitizePhpExtensions,
  resolvePhpConfig,
  isSupportedPhpVersion,
  SUPPORTED_PHP_VERSIONS,
  DEFAULT_PHP_VERSION,
  PHP_PRESETS,
} from './php-site.constants';

describe('supported PHP versions', () => {
  it('offers the latest releases (8.5, 8.4) newest-first', () => {
    expect(SUPPORTED_PHP_VERSIONS).toContain('8.5');
    expect(SUPPORTED_PHP_VERSIONS).toContain('8.4');
    // newest-first ordering: 8.5 before 8.4 before 8.3.
    expect(SUPPORTED_PHP_VERSIONS.indexOf('8.5')).toBeLessThan(SUPPORTED_PHP_VERSIONS.indexOf('8.4'));
    expect(SUPPORTED_PHP_VERSIONS.indexOf('8.4')).toBeLessThan(SUPPORTED_PHP_VERSIONS.indexOf('8.3'));
  });

  it('default is a supported version (8.4)', () => {
    expect(DEFAULT_PHP_VERSION).toBe('8.4');
    expect(isSupportedPhpVersion(DEFAULT_PHP_VERSION)).toBe(true);
  });

  it('isSupportedPhpVersion accepts the new versions and rejects EOL/garbage', () => {
    expect(isSupportedPhpVersion('8.5')).toBe(true);
    expect(isSupportedPhpVersion('8.4')).toBe(true);
    expect(isSupportedPhpVersion('5.6')).toBe(false);
    expect(isSupportedPhpVersion('9.9')).toBe(false);
    expect(isSupportedPhpVersion(null)).toBe(false);
  });

  it('every supported version builds a valid FROM tag for both apache and fpm', () => {
    for (const v of SUPPORTED_PHP_VERSIONS) {
      expect(buildPhpDockerfile({ version: v, webServer: 'apache', extensions: [] }))
        .toContain('-apache');
      expect(buildPhpDockerfile({ version: v, webServer: 'nginx', extensions: [] }))
        .toContain('-fpm');
    }
  });
});

describe('buildPhpDockerfile', () => {
  it('apache (default): mod_php image + a2enmod + base pack', () => {
    const df = buildPhpDockerfile({ version: '8.3', webServer: 'apache', extensions: [] });
    expect(df).toContain('-apache');
    expect(df).toContain('a2enmod rewrite');
    expect(df).toContain('pdo_mysql');
    expect(df).toContain('EXPOSE 80');
  });

  it('nginx: php-fpm image, no a2enmod, exposes 9000', () => {
    const df = buildPhpDockerfile({ version: '8.3', webServer: 'nginx', extensions: [] });
    expect(df).toContain('-fpm');
    expect(df).not.toContain('a2enmod');
    expect(df).toContain('EXPOSE 9000');
  });

  it('docker extension (soap) adds it to docker-php-ext-install + its apt lib', () => {
    const df = buildPhpDockerfile({ version: '8.3', webServer: 'apache', extensions: ['soap'] });
    expect(df).toContain('soap');
    expect(df).toContain('libxml2-dev');
    expect(df).not.toContain('pecl install soap');
  });

  it('pecl extension (redis) → pecl install + docker-php-ext-enable, not docker-php-ext-install', () => {
    const df = buildPhpDockerfile({ version: '8.3', webServer: 'apache', extensions: ['redis'] });
    expect(df).toContain('pecl install redis');
    expect(df).toContain('docker-php-ext-enable redis');
  });

  it('drops unknown extensions', () => {
    const df = buildPhpDockerfile({ version: '8.3', webServer: 'apache', extensions: ['totally-fake', 'soap'] });
    expect(df).not.toContain('totally-fake');
    expect(df).toContain('soap');
  });
});

describe('buildPhpIni', () => {
  it('renders the set keys only', () => {
    const ini = buildPhpIni({ memory_limit: '256M', timezone: 'Europe/Paris' });
    expect(ini).toContain('memory_limit = 256M');
    expect(ini).toContain('date.timezone = Europe/Paris');
    expect(ini).not.toContain('upload_max_filesize');
  });
  it('empty config → just the header', () => {
    expect(buildPhpIni(null).trim()).toMatch(/Generated by DockControl/);
  });
});

describe('buildNginxConf', () => {
  it('FastCGI to the UNIQUE fpm container name (not the shared `app` alias)', () => {
    const conf = buildNginxConf('dockcontrol-my-site-fpm');
    expect(conf).toContain('fastcgi_pass dockcontrol-my-site-fpm:9000');
    expect(conf).not.toContain('fastcgi_pass app:9000'); // cross-tenant collision
    expect(conf).toContain('root /var/www/html');
  });
  it('guards php execution with try_files =404', () => {
    expect(buildNginxConf('x-fpm')).toContain('try_files $fastcgi_script_name =404');
  });
  it('derives client_max_body_size from the php.ini upload limit (never below 64m)', () => {
    expect(buildNginxConf('x-fpm', {})).toContain('client_max_body_size 64m');
    expect(buildNginxConf('x-fpm', { upload_max_filesize: '256M' })).toContain('client_max_body_size 256m');
    expect(buildNginxConf('x-fpm', { post_max_size: '512M' })).toContain('client_max_body_size 512m');
    expect(buildNginxConf('x-fpm', { upload_max_filesize: '1G' })).toContain('client_max_body_size 1024m');
    // a smaller-than-default limit must NOT shrink nginx below the 64m floor.
    expect(buildNginxConf('x-fpm', { upload_max_filesize: '8M' })).toContain('client_max_body_size 64m');
  });
});

describe('resolvePhpConfig', () => {
  it('preset wordpress expands into its extensions + ini', () => {
    const r = resolvePhpConfig({ preset: 'wordpress' });
    expect(r.preset).toBe('wordpress');
    expect(r.extensions).toEqual(expect.arrayContaining(PHP_PRESETS.wordpress.extensions));
    expect(r.ini.memory_limit).toBe('256M');
  });

  it('explicit extensions merge ON TOP of the preset', () => {
    const r = resolvePhpConfig({ preset: 'symfony', extensions: ['redis'] });
    expect(r.extensions).toEqual(expect.arrayContaining(['mbstring', 'xsl', 'redis']));
  });

  it('sanitizes ini values (rejects injection / bad values)', () => {
    const r = resolvePhpConfig({ ini: { memory_limit: '256M', upload_max_filesize: 'evil\ninjection = x' } as any });
    expect(r.ini.memory_limit).toBe('256M');
    expect(r.ini.upload_max_filesize).toBeUndefined();
  });

  it('webServer defaults to apache; nginx honoured', () => {
    expect(resolvePhpConfig({}).webServer).toBe('apache');
    expect(resolvePhpConfig({ webServer: 'nginx' }).webServer).toBe('nginx');
  });
});

describe('sanitizePhpExtensions', () => {
  it('dedups + drops unknown', () => {
    expect(sanitizePhpExtensions(['soap', 'soap', 'nope'])).toEqual(['soap']);
  });
});
